### ISSUE TITLE
Got this error while trying to set it up

### ISSUE THREAD

**Issue by Oluwasetemi** [BolajiOlajide/koii#9]
![image](https://user-images.githubusercontent.com/10030028/68322873-87ca6600-00c4-11ea-91a2-f64265225d95.png)

**Comment by BolajiOlajide** [comment]
Hey @Oluwasetemi ,

Thanks for raising this issue. From my investigation, it appears we didn't cater for deeply nested routes - I've pushed and published a fix for this. Kindly update your version of `koii` to `2.0.2` and let me know if you still experience this or not 🙂.

Thanks.

**Comment by BolajiOlajide** [comment]
Apologies you had to experience this.

**Comment by BolajiOlajide** [comment]
Hey @Oluwasetemi,

Would appreciate a response whenever you can - thanks.

**Comment by BolajiOlajide** [comment]
I'm going to assume this has been fixed. If you still see this problem, kindly feel free to reopen this issue.
